### ISSUE TITLE
窗（1x1 斜窗）应为 窗（1x3 斜窗）

### ISSUE THREAD

**Issue by cacan180** [BKN46/stormworks-translate-chn#5]
def_window_small_angle_name		Small Angled Window	窗（1x1 斜窗）

**Comment by cacan180** [comment]
![1](https://user-images.githubusercontent.com/48651501/120516495-05219e00-c402-11eb-934e-cdc4a34f4e65.png)
![2](https://user-images.githubusercontent.com/48651501/120516501-06eb6180-c402-11eb-881e-285931d861a5.png)

**Comment by BKN46** [comment]
感谢反馈，已解决
